apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oh5n56i07-python 
  janus-idp.io/tekton: oh5n56i07-python
  backstage.io/kubernetes-id: oh5n56i07-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oh5n56i07-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml