apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oh5n56i07-python
  janus-idp.io/tekton: oh5n56i07-python
  backstage.io/kubernetes-id: oh5n56i07-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oh5n56i07-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
