apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oh5n56i07-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oh5n56i07-python 
  name: oh5n56i07-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oh5n56i07-python 
